### PR TITLE
Added: Stats

### PR DESCRIPTION
**Pull request by starrify**
Personally I don't see it as a duplication of the existing downloader stats, since a spider might not have all of its requests sent through Crawlera.

### CODE REVIEW

**Comment by redapple** [comment]
@starrify , I agree this is important debug information. Thanks!

I see that you've chosen stat names similarly to `downloader` stats, .e.g
```
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 1916,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/404': 1,
```

I don't know what others think but my preference goes to something close to what `scheduler/...` stats are, that stats are counts anyway (virtually all the time) so no special need to have "count" in the name, i.e.
```
'crawlera/request': 32
'crawlera/request/method/GET': 18,
'crawlera/response/banned': 16,
'crawlera/response': 18,
'crawlera/response/status/200': 14,
'crawlera/response/error': 24,
'crawlera/response_error/noslaves': 10,
```

In particular, you are using `'crawlera/response_count'`, but `'crawlera/response_error'` and `'crawlera/response_error_count/<error>'`, so that would appear inconsistent IMHO.

**Comment by starrify** [comment]
@redapple Thanks a lot for the advice 😄 👍 The PR has been updated.

**Comment by redapple** [comment]
LGTM

**Comment by eLRuLL** [comment]
LGTM 👍 , should we make it pass codecov or just merge? @redapple ?

**Pull request merged**
