### PR TITLE
fix#77: protocol in CRAWLERA_URL

### LINKED ISSUE #77: Enhance exception description when CRAWLERA_URL is missing the scheme
If you inadvertently set you `CRAWLERA_URL` setting without the URL scheme like:

 ```CRAWLERA_URL = "proxy.crawlera.com:8010" ```

You'll receive a non-descriptive twisted exception when trying to crawl `http://`

```shell
Traceback (most recent call last):
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/bin/scrapy", line 10, in <module>
    sys.exit(execute())
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/scrapy/commands/shell.py", line 74, in run
    shell.start(url=url, redirect=not opts.no_redirect)
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/scrapy/shell.py", line 47, in start
    self.fetch(url, spider, redirect=redirect)
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/scrapy/shell.py", line 120, in fetch
    reactor, self._schedule, request, spider
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()
  File "/home/raphael/.virtualenvs/myproject-jQmK5Pxo/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web.error.SchemeNotSupported: Unsupported scheme: b''
```

I think a good approach would be to identify the lack of the scheme on `CRAWLERA_URL` and throw a descriptive expection. This can be done at  `spider_open` signal we listen to on `CrawleraMiddleware`.

### PR DESCRIPTION
**Pull request by ejulio**
Fix #77 
Instead of a better exception I log an warning that the URL was updated.
If no protocol is provided, `http://` is set.
If the protocol was `https://` then it is updated to `http://`

### CODE REVIEW

**Comment by hcoura** [comment]
Not sure I agree with `If the protocol was https:// then it is updated to http://`, if crawlera in the future decides to change the protocol of the proxy it will break.

I am ok with adding `http` if no protocol provided. Would leave the rest as is and not make any assumption on which protocols crawlera supports.

**Comment by ejulio** [comment]
Makes sense.
I'll at least log a warning that protocol is https, what do you think?

**Comment by dangra** [comment]
Is it common to mistakenly add `https://` as protocol to Crawlera URL?  I don't mind logging a warning about it but surely the middleware shouldn't change it to `http://`.

**Comment by ejulio** [comment]
hey @dangra and @hcoura . Fixed the issue with _https://_
The CI is breaking because the tests install scrapy 1.7 and there was a change in the API.
I can set requirements to scrapy 1.6 here, fix the tests, or create another issue to fix it.
What do you think?

**Comment by Gallaecio** [comment]
https://github.com/scrapy-plugins/scrapy-crawlera/commit/55de303f774f0b695bc30af970be8486bb807313 fixed the test issue, rebasing against master should do the job.

**Comment by ejulio** [comment]
Updated, thanks @Gallaecio

**Comment by dangra** [comment]
thanks @ejulio and everyone here !

**Pull request merged**
