### PR TITLE
Lower recommended download timeout to 190s

### PR DESCRIPTION
**Pull request by redapple**

### CODE REVIEW

**Comment by eLRuLL** [comment]
I checked crawlera's configurations and looks like it was already changed that way on their side, I think we should also update the user documentation

https://github.com/scrapinghub/doc.scrapinghub.com/pull/139

**Comment by eLRuLL** [comment]
Also as I understand, that is the timeout per request in crawlera, which means that scrapy should be able to wait for the retries too, and `X-Crawlera-Retries` defaults to 5, so our default should be `150000`, @amleczko what do you think?

**Comment by redapple** [comment]
Sorry @eLRuLL , @amleczko , I'm not sure I'm following https://github.com/scrapy-plugins/scrapy-crawlera/pull/19#issuecomment-219729968. Which value should be `150000`?

In http://doc.scrapinghub.com/crawlera.html#using-crawlera-with-scrapy ,
`DOWNLOAD_TIMEOUT = 300` (5 minutes) is recommended for scrapy settings,
which, as far as I understand, is supposed to account for the initial try + 5 retries.

`CrawleraMiddleware's` `download_timeout` attribute -- initialized with `CRAWLERA_DOWNLOAD_TIMEOUT`'s value -- sets [scrapy's Requests `download_timeout` in `meta` dict](https://github.com/scrapy-plugins/scrapy-crawlera/blob/master/scrapy_crawlera.py#L126) for requests going through Crawlera, which is that same timeout above.

Or @eLRuLL do you mean the recommended value in http://doc.scrapinghub.com/crawlera.html#using-crawlera-with-scrapy and for `CRAWLERA_DOWNLOAD_TIMEOUT` should be `30s + 5 x 30s = 180s` (30s being default for X-Crawlera-Timeout)?

**Comment by eLRuLL** [comment]
the second part, sorry I didn't count the first attempt, it would be `180s`.

**Comment by redapple** [comment]
@eLRuLL , @amleczko , updateed to 190s, a bit more than `30s + 5 x 30s = 180s`

**Comment by eLRuLL** [comment]
great I agree with `190`, @redapple can we squash the commits to merge? after the merge we should also update the documentation: https://github.com/scrapinghub/doc.scrapinghub.com/pull/139/files

**Comment by redapple** [comment]
@eLRuLL , rebased

**Pull request merged**
