### PR TITLE
middleware.py: Add spider info for each logging

### PR DESCRIPTION
**Pull request by refeed**
Add spider info for each logging by adding `extra` argument
to logging calls.

Closes https://github.com/scrapy-plugins/scrapy-crawlera/issues/46

### CODE REVIEW

**Comment by deti** [comment]
@redapple could you have a look at it?

**Comment by redapple** [comment]
@deti , looks good to me.

**Comment by deti** [comment]
Many thanks @redapple !

**Comment by eLRuLL** [comment]
@refeed for merging this PR, please add some tests. Thanks

**Pull request closed without merging**
